spring.application.name=Matching-service
server.port=8084

# The matching service doesn't need a DB, just Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Enable Feign Clients (SB 4 specific)
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000
